name: Docker Image CI

on:
  push:
    paths: 'Backend/reSign/**'

jobs:
  build-docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build API docker image
      run: |
        cd Backend/reSign
        docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
        docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_IMAGE }}:latest
        docker push ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_IMAGE }}
        docker logout
