name: Docker Image CI

on:
  push:
    paths: 'Backend/reSign/**'

jobs:
  build-docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build API docker image
      run: |
        cd Backend/reSign/ReSign.WebAPI
        pwd
        ls
