name: Docker Image CI

on:
  push:
    paths: 'Backend/reSign/**'

jobs:
  build-docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build API docker image
      run: |
        cd Backend/reSign
        docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_IMAGE }}:latest
        
    - name: Login to the Container registry (docker)
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
        
    - name: Push docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_IMAGE }}
        docker logout
    
    
    - name: Install ssh key
      uses: caberger/install-ssh-key@v1.0
      with:
          ssh-private-key:  ${{ secrets.SSH_PRIVATE_KEY }}
          user: ${{ secrets.REMOTE_USER }}
          server: ${{ secrets.REMOTE_HOST }}
          alias: server

    - name: Create docker container
      run: ssh server "docker run --name resign-backend -p 8080:80 -p 8081:443 nydery/resign_backend:latest"
