name: Docker Image CI

on:
  push:
    paths: 'Backend/reSign/**'
  workflow_dispatch:

env:
  DOCKER_USER: nydery
  DOCKER_IMAGE: resign_backend
  DOCKER_CONTAINER: resign-backend
  

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build API docker image
      run: |
        cd Backend/reSign
        docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_IMAGE }}:latest
    - name: Login to the Container registry (docker)
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Push docker image
      run: |
        docker push ${{ env.DOCKER_USER }}/${{ env.DOCKER_IMAGE }}
        docker logout
    
  start-docker-container-on-vm:
    needs:
      - build-and-push-docker-image
    runs-on: ubuntu-latest
    steps:
      - name: Install ssh key
        uses: caberger/install-ssh-key@v1.0
        with:
            ssh-private-key:  ${{ secrets.SSH_PRIVATE_KEY }}
            user: ${{ secrets.REMOTE_USER }}
            server: ${{ secrets.REMOTE_HOST }}
            alias: server

      - name: Remove existing container
        run: |
          ssh server "sudo docker stop ${{ env.DOCKER_CONTAINER }} || echo 'Container doesn't exist!'"
          ssh server "sudo docker rm ${{ env.DOCKER_CONTAINER }} || echo '.'"

      - name: Create docker container
        run: ssh server "sudo docker run -d --name ${{ env.DOCKER_CONTAINER }} -p 8080:80 -p 8081:443 ${{ env.DOCKER_USER }}/${{ env.DOCKER_IMAGE }}:latest"
