name: Docker Image CI

on:
  push:
    paths: 'Backend/reSign/**'

jobs:
  build-docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Change directory to WebAPI
      run: cd reSign/Backend/reSign/ReSign.WebAPI
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag resign-backend:latest
