name: Frontend-UI CD

on: 
  push:
    paths: 'Frontend/fcis-ui/**'
    
jobs:
  deploy-website:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Deploy to OraVM
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: "Frontend/fcis-ui/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
